Algoritmo "teste"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/08/2025
Var
// Seção de Declarações das variáveis 
    i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     para i de 5 ate 1 passo -1 faca
          escreval("Valor de  i: ", i)
     fimpara

Fimalgoritmo