Algoritmo "soma"

 // Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes
// números.
Var
          x, y, soma : inteiro


Inicio

          escreval("Vamos fazer uma soma de dois números inteiro: ")
          escreva("Digite o valor de X: ")
          leia(x)
          escreva("Digite o valor de Y: ")
          leia(y)

          soma <-  x + y
          
          escreval("SOMA = ", soma)


Fimalgoritmo